import Vue from 'vue'
import Vuetify, {
    VApp,
    VContainer,
    VCard,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VRow,
    VCol,
    VForm,
    VTextField,
    VList,
    VListItem,
    VListItemTitle,
    VListItemSubtitle,
    VListItemIcon,
    VListItemGroup,
    VSubheader,
    VIcon,
    VAvatar,
    VImg,
    VSpacer,
    VBtn,
    VSimpleTable,
    VDialog,
    VSelect,
    VListGroup,
    VListItemContent,
    VDivider,
    VOverlay,
    VBadge,
    VCheckbox,
    VInput,
    VSnackbar,
    VSwitch,
    VMenu,
    VDatePicker,
    VTimePicker,
    VTextarea,
    VProgressCircular,
} from 'vuetify/lib'



Vue.use(Vuetify, {
    components: {
        VApp,
        VContainer,
        VCard,
        VCardTitle,
        VCardText,
        VCardActions,
        VRow,
        VCol,
        VForm,
        VTextField,
        VList,
        VListItem,
        VListItemTitle,
        VListItemSubtitle,
        VListItemIcon,
        VListItemGroup,
        VSubheader,
        VIcon,
        VAvatar,
        VImg,
        VSpacer,
        VBtn,
        VCardSubtitle,
        VSimpleTable,
        VDialog,
        VSelect,
        VListGroup,
        VListItemContent,
        VDivider,
        VOverlay,
        VBadge,
        VCheckbox,
        VInput,
        VSnackbar,
        VSwitch,
        VMenu,
        VDatePicker,
        VTimePicker,
        VTextarea,
        VProgressCircular,
    }
})

export default new Vuetify({
})
