name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: step1
        run: echo "test"
      - name: nametest
      - id: step2
        run: ls
        run: cd ..
        run: ls
        run: cd ..
        run: ls
      # - id: step3
      #   run: docker build .
      # - id: step4
      #   run: echo "docker build出来た？"
