name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: yarn build
        run: | #
          ls
          cd web
          docker build .
          yarn global add @vue/cli@5.0.4
          yarn build
          docker ps
      - name: move files
        run: | #
          cd web
          ls
      - name: collect static
        run: | #
          cd api
          ls
      - name: heroku release
        run : | #
          ls
