name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - id: step1
      #   run: echo "test"
      - name: test
      # - id: step2
        # run: ls
        run: | #
          ls
          cd ..
      - name: test2
        run: | #
          ls
          cd web
      - name: test3
        run: | #
          ls
          cd web
          docker build .
        # run: cd ..
        # run: ls
      # - id: step3
      #   run: docker build .
      # - id: step4
      #   run: echo "docker build出来た？"
