name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          VUE_APP_AUTH_REDIRECT_URI: ${{ secrets.VUE_APP_AUTH_REDIRECT_URI }}
          NODE_ENV: production
          VUE_APP_DEV_REDIS_URL: ${{ secrets.VUE_APP_DEV_REDIS_URL }}
      - name: yarn build
        run: | #
          ls
          cd web
          docker build .
          rm -rf node_modules package-lock.json && npm install
          yarn build
          docker ps
      - name: move files
        run: | #
          mv web/dist/templates/index.html api/templates
          mv web/dist/static/css api/staticfiles/
          mv web/dist/static/fonts api/staticfiles/
          mv web/dist/static/img api/staticfiles/
          mv web/dist/static/js api/staticfiles/
          cd api
          ls
      - name: check static
        run: | #
          cd api/staticfiles
          ls
      - name: collect static
        run: | #
          cd api
          docker build .
          python manage.py collectstatic
          ls
          cd staticfiles
          ls
      - name: heroku release
        run : | #
          ls

  # test:
  # deploy:
  #   needs:
  #     - build
  #     # - test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 7
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: heroku deploy
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}
  #         usedocker: true
  #         docker_build_args: |
  #           NODE_ENV
  #       env:
  #         NODE_ENV: production
  #         # SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
  #     - name: deploy
  #       runs: | #
  #         ls
  #         cd web
  #         ls
  #         cd dist
  #         ls
